language: generic
sudo : required

services: 
  - docker 

before_install:
  - docker build -t victorzhz/docker-react -f Dockerfile.dev .

scripts: 
  - docker run -e CI=true victorzhz/docker-react npm run test
  